to remove this                              msg[1]['run_id'] = self.run_id
from the monitoring router, the interchange should fully construct these
messages - c.f. how the task wrapper knows the run id

so add run id as an interchange parameter and populate there

... which means htex needs to know about run_ids

... which is fine as it knows about monitoring generally, in order to
send the messages into monitoring...

this is tested by
test_row_counts
which fails without the run_id populated
due to:

> sqlite3.IntegrityError: NOT NULL constraint failed: node.run_id

in the database manager.